import { makeStyles, createStyles } from "@material-ui/core/styles";

const useStyles = makeStyles((theme) =>
    createStyles({
        navbar: {
            width: '100%',
            height: '10%',
            //backgroundColor: theme.palette.primary.light,
            position: 'fixed',
            borderBottom: '1px solid #E5E7E9',
            top: 0,
            left: 0,
            zIndex: 99,
            display: 'flex',
            padding: '0 20px ',
        },
        sidebar: {
            width: '70px',
            height: '90vh',
            backgroundColor: '#fff',
            position: 'fixed',
            top: '10%',
            left: 0,
            zIndex: 0,
            display: 'flex',
            flexDirection: 'column',
            '&:hover': {
                cursor: 'pointer',
                width: '250px',
                zIndex: 55,
            },
        },
        sidebarBig: {
            width: '250px',
            height: '90vh',
            backgroundColor: '#fff',
            position: 'fixed',
            top: '10%',
            left: 0,
            zIndex: 55,
            display: 'flex',
            flexDirection: 'column',
            '&:hover': {
                cursor: 'pointer',
                width: '250px',
                zIndex: 55,
            },
        },
        topbar: {
            width: '100%',
            height: '50px',
            position: 'absolute',
            borderBottom: '1px inset #E5E7E9',
            backgroundColor: '#EAEDED',
            top: 0,
            left: 0,
            zIndex: 33,
        },
        rightbar: {
            width: '50px',
            height: '90vh',
            borderLeft: '1px solid #E5E7E9',
            backgroundColor: '#fff',
            position: 'fixed',
            top: '10%',
            right: 0,
            zIndex: 55,
        },
        link: {
            color: theme.palette.primary.main,
            zIndex: 0,
            padding: '10px 25px',
            textDecoration: 'none',
            display: 'flex',
            alignItems: 'center',
            textAlign: 'center',
            '&:hover': {
                backgroundColor: theme.palette.secondary.light,
                color: '#fff',
                textDecoration: 'none',
                borderTopRightRadius: 20,
                borderBottomRightRadius: 20,
            },
        },
        activeLink: {
            color: '#E74C3C',
            zIndex: 0,
            padding: '10px 25px',
            borderTopRightRadius: 10,
            borderBottomRightRadius: 10,
            textDecoration: 'none',
            display: 'flex',
            textAlign: 'center',
            alignItems: 'center',
            '&:hover': {
                backgroundColor: '#F5B7B1',
                textDecoration: 'none',
            },
        },
        btn: {
            margin: '30px 5px',
            paddingLeft: 15, 
            paddingTop: 10,
            paddingBottom: 10,
            width: 'auto',
            display: 'flex', 
            flexDirection: 'row', 
            alignItems: 'center', 
            backgroundColor: '#fff',
            boxShadow: '0px 0px 0px 0.5px rgb(0, 0, 0, 0.1)', 
            borderRadius: '30px',
        },
        //btn2: {
        //    margin: 25, 
        //    display: 'flex', 
        //    flexDirection: 'row', 
        //    alignItems: 'center', 
        //    backgroundColor: 'grey', 
        //    backgroundRadius: '30px',
        //},
    }),
);

export default useStyles;
